### ISSUE TITLE
请问可以在对方撤回之后显示一条提示信息吗

### ISSUE THREAD

**Issue by bling-yshs** [xh321/LiteLoaderQQNT-Anti-Recall#1]
请问可以在对方撤回之后显示一条提示信息吗？比如对方撤回了一条消息：内容为:xxx 这样子。

如果显示内容很难的话，只提示对方撤回了一条消息也行，不然不知道对面撤没撤回挺尴尬的。

**Comment by xh321** [comment]
我是打算这么做的，但是还没弄清楚qqnt那个灰色提示应该怎么发送，总不能弹个窗吧（乐

**Comment by xh321** [comment]
你如果在哪看见类似于撤回提示的那种灰色提示，最好是能稳定触发的，跟我说，我去看看他IPC包

**Comment by Ritchie1108** [comment]
类似繁化姬那样直接在原消息底下加文字说明的也不是不行, 不过还是和之前提到的存储方式一样, 对用户侧来说可能存在安全风险, 如果做的话记得在说明清楚

**Comment by xh321** [comment]
> 类似繁化姬那样直接在原消息底下加文字说明的也不是不行, 不过还是和之前提到的存储方式一样, 对用户侧来说可能存在安全风险, 如果做的话记得在说明清楚

繁化姬其实也没有储存，由于NTQQ的特性，滚动屏幕后会重新更新元素，繁化姬他也会失效的（可以试一下，先繁体化，然后滚动屏幕，再回去看的时候，繁化姬的提示就消失了）。
实现这种效果不难，但还是不太方便的样子。

**Comment by xh321** [comment]
已经更新了，可以看看效果

**Comment by bling-yshs** [comment]
> 已经更新了，可以看看效果

我这里不知道为什么没有效果qwq..
![image](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/41812674/d386a453-f58f-4eb9-8e69-bd87c576ce8c)

**Comment by xh321** [comment]
> > 已经更新了，可以看看效果
> 
> 我这里不知道为什么没有效果qwq.. ![image](https://user-images.githubusercontent.com/41812674/251974413-d386a453-f58f-4eb9-8e69-bd87c576ce8c.png)

啊啊，不是liteloader更新啊，是插件更新，更新后，撤回的消息会保留并在后面附加一句话[该消息已被撤回]

**Comment by bling-yshs** [comment]
> > > 已经更新了，可以看看效果
> > 
> > 
> > 我这里不知道为什么没有效果qwq.. ![image](https://user-images.githubusercontent.com/41812674/251974413-d386a453-f58f-4eb9-8e69-bd87c576ce8c.png)
> 
> 啊啊，不是liteloader更新啊，是插件更新，更新后，撤回的消息会保留并在后面附加一句话[该消息已被撤回]

不是的，不是的，我代码更新过了的，这个图这是说明一下我的LL版本。
![image](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/41812674/a8753e23-91b1-419b-a372-f64835dc328d)
![image](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/41812674/37cde6b3-69e1-4c43-b3ad-31b14807224c)

其它插件我也都全关了，但是就是没效果，群聊私聊都不会有提示

**Comment by histion** [comment]
> > > > 已经更新了，可以看看效果
> > > 
> > > 
> > > 我这里不知道为什么没有效果qwq.. ![image](https://user-images.githubusercontent.com/41812674/251974413-d386a453-f58f-4eb9-8e69-bd87c576ce8c.png)
> > 
> > 
> > 啊啊，不是liteloader更新啊，是插件更新，更新后，撤回的消息会保留并在后面附加一句话[该消息已被撤回]
> 
> 不是的，不是的，我代码更新过了的，这个图这是说明一下我的LL版本。 ![image](https://user-images.githubusercontent.com/41812674/252107626-a8753e23-91b1-419b-a372-f64835dc328d.png) ![image](https://user-images.githubusercontent.com/41812674/252109515-37cde6b3-69e1-4c43-b3ad-31b14807224c.png)
> 
> 其它插件我也都全关了，但是就是没效果，群聊私聊都不会有提示

同样，更新后撤回一样没有提示。。

**Comment by xh321** [comment]
> > > > > 已经更新了，可以看看效果
> > > > 
> > > > 
> > > > 我这里不知道为什么没有效果qwq.. ![image](https://user-images.githubusercontent.com/41812674/251974413-d386a453-f58f-4eb9-8e69-bd87c576ce8c.png)
> > > 
> > > 
> > > 啊啊，不是liteloader更新啊，是插件更新，更新后，撤回的消息会保留并在后面附加一句话[该消息已被撤回]
> > 
> > 
> > 不是的，不是的，我代码更新过了的，这个图这是说明一下我的LL版本。 ![image](https://user-images.githubusercontent.com/41812674/252107626-a8753e23-91b1-419b-a372-f64835dc328d.png) ![image](https://user-images.githubusercontent.com/41812674/252109515-37cde6b3-69e1-4c43-b3ad-31b14807224c.png)
> > 其它插件我也都全关了，但是就是没效果，群聊私聊都不会有提示
> 
> 同样，更新后撤回一样没有提示。。

已解决，新版修改了id的格式

**Comment by xh321** [comment]
![image](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/37585529/37176a51-a680-44d0-a4f8-72a165c031e0)

**Comment by Ritchie1108** [comment]
> 

嗯我知道, 怪我没表述清楚, 本意是想说类似"存储"的风险一样, 存在"篡改显示消息"的风险

**Comment by Ritchie1108** [comment]
> > 类似繁化姬那样直接在原消息底下加文字说明的也不是不行, 不过还是和之前提到的存储方式一样, 对用户侧来说可能存在安全风险, 如果做的话记得在说明清楚
> 
> 繁化姬其实也没有储存，由于NTQQ的特性，滚动屏幕后会重新更新元素，繁化姬他也会失效的（可以试一下，先繁体化，然后滚动屏幕，再回去看的时候，繁化姬的提示就消失了）。 实现这种效果不难，但还是不太方便的样子。


嗯我知道, 怪我没表述清楚, 本意是想说类似"存储"的风险一样, 存在"篡改显示消息"的风险

**Comment by xh321** [comment]
> 

毕竟是开源的嘛，怎样篡改你也能看见😉
