### ISSUE TITLE
Linux版 防撤回有bug

### ISSUE THREAD

**Issue by yigekuyou** [xh321/LiteLoaderQQNT-Anti-Recall#10]
[linuxqq 最新版](https://dldir1.qq.com/qqfile/qq/QQNT/ad5b5393/linuxqq_3.1.2-13107_x86_64.AppImage)，无热更新，[bwrap启动](https://github.com/yigekuyou/sandbox/blob/main/startqqnt.sh)
[linux.LOG](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/files/12266248/linux.LOG)
OS: openSUSE Tumbleweed 20230803 x86_64
Kernel: 6.4.6-1-default
Locale: zh_CN.UTF-8
DE: KDE Plasma 5.27.7
WM: KWin (Wayland)

**Comment by yigekuyou** [comment]
需要补充吗

**Comment by xh321** [comment]
已解决
