### ISSUE TITLE
新版本QQ启用本插件会导致部分群不显示消息

### ISSUE THREAD

**Issue by Evsdrg** [xh321/LiteLoaderQQNT-Anti-Recall#100]
如题，第一张图为启用，第二张图为禁用，除此之外无任何操作，未启用任何其他插件
LL1.2.3、QQNT9.9.16-29271、插件0.2.47
![图片](https://github.com/user-attachments/assets/b992aaea-88af-4bb0-a61a-b6b53f83efc8)
![图片](https://github.com/user-attachments/assets/be29c84a-ce08-4d66-9738-080afd02193a)

**Comment by Evsdrg** [comment]
坏了没看到适用版本😂

**Comment by gxlydlyf** [comment]
这应该是出错了，我在QQNT9.9.16-29456也没问题
