### ISSUE TITLE
配置界面一片空白

### ISSUE THREAD

**Issue by javilak** [xh321/LiteLoaderQQNT-Anti-Recall#11]
插件仅开启本模块的情况下，配置界面一片空白啥都没有

* qq版本 9.9.1-15717
* 插件版本 0.28
* LiteLoader版本 0.50
![image](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/47470153/1c4442d7-86aa-4665-8879-44e0abae49a9)

**Comment by bty552** [comment]
我也是

**Comment by xxtg666** [comment]
同问

**Comment by xh321** [comment]
能否F12看一下有没有报错？

**Comment by xxtg666** [comment]
![image](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/68174188/4f0772a2-9b31-4e30-958a-00403d201a88)
设置界面空白报错

**Comment by xxtg666** [comment]
![image](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/68174188/7a6f474d-f170-47ad-aa0e-c7c28e01a654)
撤回无提示报错

**Comment by xh321** [comment]
已更新，可以看看是否解决

**Comment by xxtg666** [comment]
可用
