### ISSUE TITLE
开启数据库导致消息加载卡顿

### ISSUE THREAD

**Issue by gandyli** [xh321/LiteLoaderQQNT-Anti-Recall#16]
开启数据库使用了一段时间后 QQNT 出现显著的卡顿，关闭后卡顿消失，数据库文件夹大小约 350K。

**Comment by xh321** [comment]
关闭数据库储存就能恢复对吗，如果是这样我正在考虑优化，请等待版本更新

**Comment by xh321** [comment]
已更新，可以检查一下是否满足
修改了数据库储存的结构，会导致之前的反撤回记录失效，建议清空数据库重新观察几天

**Comment by xh321** [comment]
如果没问题的话先关闭issue了

**Comment by ayakasuki** [comment]
我也是 QQNT很卡顿 排除了下插件 关掉防撤回就不卡了

**Comment by ayakasuki** [comment]
> 我也是 QQNT很卡顿 排除了下插件 关掉防撤回就不卡了

更新后好很多

**Comment by xh321** [comment]
> > 我也是 QQNT很卡顿 排除了下插件 关掉防撤回就不卡了
> 
> 更新后好很多

防撤回最近几个版本都在解决卡顿问题，现在应该已经不会再卡了
