### ISSUE TITLE
消息时间

### ISSUE THREAD

**Issue by shi-an** [xh321/LiteLoaderQQNT-Anti-Recall#17]
这个时间能不能 不包在红框里
![image](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/79352488/84bf16a9-73e2-4fa7-8356-e3373d194374)

**Comment by xh321** [comment]
这个是没办法的，只有在最外层才有阴影效果，再里面一层会被覆盖无法显示阴影。可以尝试让显示时间的插件做一个兼容。
