### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by shi-an** [xh321/LiteLoaderQQNT-Anti-Recall#18]
9.9.2.15962    +1被撤回的消息     撤回提示显示已撤回
![image](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/79352488/e9ab0ec9-77a4-465d-8139-f8bb8cb26734)

**Comment by xh321** [comment]
最新release已尝试修复，请检查

**Comment by xh321** [comment]
如果没问题的话先关闭issue了
