### ISSUE TITLE
自己的消息无法防撤回 

### ISSUE THREAD

**Issue by douziovo** [xh321/LiteLoaderQQNT-Anti-Recall#19]
在手机QQ上撤回自己的消息QQNT无法防撤回 其他人的消息则正常防撤回
在腾讯QQ中搭配RevokeMsgPatcher.v1.6则可以显示

手机QQ版本8.9.73
腾讯QQ版本9.7.11
QQNT版本9.9.1-15820 (64位)
LiteLoaderQQNT-Anti-Recall版本0.2.13
LiteLoaderQQNT版本https://github.com/mo-jinran/LiteLoaderQQNT/tree/3f479a1bdd99eb4bb3cc8bcf5f378e386554309f

**Comment by xh321** [comment]
设计如此，故意绕过了自己的消息，不然防撤回自己的消息也太怪了

**Comment by xh321** [comment]
不过我也可以在配置里加一个开关，是否显示自己撤回的消息

**Comment by douziovo** [comment]
那样太感激不过了

**Comment by xh321** [comment]
0.2.14版本已增加该功能
