### ISSUE TITLE
有关反撤回的限制

### ISSUE THREAD

**Issue by xh321** [xh321/LiteLoaderQQNT-Anti-Recall#2]
正如README中说明的那样，渲染层拦截的反撤回只是暂时的，重新加载数据后就会被“覆盖”——从逻辑层获取的数据中，仅包含撤回提示，并不包含被撤回的消息了。
那么，要真正实现反撤回，我认为需要做到：
1. 要么从根本上拦截撤回消息包（深入逻辑层拦截），DLL劫持可以做到，但JS应该不行。
2. 要么本地储存被撤回的消息，在获取消息列表的时候patch上去。
方案一不适用于本框架，方案二过于不安全，一旦出现消息泄漏可能会导致严重后果（即使加密，也无处存放密钥）。
所以本项目能做到的，应该仅限于目前的水平了。

**Comment by xh321** [comment]
更新：目前消息会被暂存于内存中，QQNT进程的生命周期内均可正确反撤回，上述一部分限制不复存在。但是重启QQNT后反撤回仍会失效。

**Comment by mo-jinran** [comment]
我想，建议弄一个开关，跟BetterQQNT一样，将消息存在本地（不过BetterQQNT是用json存储，建议塞进QQ的消息数据库内（如果可以的话，或使用更好的数据库）
让用户自行权衡消息泄露的风险

**Comment by xh321** [comment]
> 我想，建议弄一个开关，跟BetterQQNT一样，将消息存在本地（不过BetterQQNT是用json存储，建议塞进QQ的消息数据库内（如果可以的话，或使用更好的数据库） 让用户自行权衡消息泄露的风险

正打算这么做，但大概会自己实现一下数据库，塞qq数据库一是不知道如何实现二是可能有其他问题

**Comment by Dahurica** [comment]
> 更新：目前消息会被暂存于内存中，QQNT进程的生命周期内均可正确反撤回，上述一部分限制不复存在。但是重启QQNT后反撤回仍会失效。 更新：目前已部分实现数据库储存功能，但重启QQ后还不能正确反撤回图片。

对，但是我记得最开始的版本可以直接返回所有图片，但是现在好像只能是当前窗口的消息返回，其他的都会显示易损图片

**Comment by xh321** [comment]
> > 更新：目前消息会被暂存于内存中，QQNT进程的生命周期内均可正确反撤回，上述一部分限制不复存在。但是重启QQNT后反撤回仍会失效。 更新：目前已部分实现数据库储存功能，但重启QQ后还不能正确反撤回图片。
> 
> 对，但是我记得最开始的版本可以直接返回所有图片，但是现在好像只能是当前窗口的消息返回，其他的都会显示易损图片

看readme，降级qq到9.9.7再看看

**Comment by MarisaDA-ZE** [comment]
作者您好，后续是否会更新自定义存储源的功能？我看readme提到目前版本是将数据存储在内存中的，是否可以将数据存储在MySQL等数据库中以实现撤回消息持久化？

**Comment by xh321** [comment]
> 作者您好，后续是否会更新自定义存储源的功能？我看readme提到目前版本是将数据存储在内存中的，是否可以将数据存储在MySQL等数据库中以实现撤回消息持久化？ 因为您原生的持久化貌似有些问题，在某些版本可能会出现预期之外的BUG（比如9.9.12-25765 x64），如果可以让使用者自定义存储，可能会使工具有更多的可玩性？（

自定义储存当然好，但插件不能拖着一个巨大的orm，这也太抽象了。插件要实现，在有orm时调用orm，没有就用内置的储存接口。后期可能考虑让用户自定义安装orm以支持其他储存类型。
计划中，但鉴于可能没时间做，请耐心等待
