### ISSUE TITLE
快速撤回大量消息会有消息没被反撤回

### ISSUE THREAD

**Issue by RawDiamondMC** [xh321/LiteLoaderQQNT-Anti-Recall#20]
如题

**Comment by xh321** [comment]
重新进入消息界面效果如何
以及，仅仅是没增加撤回提示，还是说这条消息实际上已经被撤回了，再也看不到了。

**Comment by RawDiamondMC** [comment]
> 重新进入消息界面效果如何 以及，仅仅是没增加撤回提示，还是说这条消息实际上已经被撤回了，再也看不到了。

重新打开qqnt之后也没显示，大概是彻底没了

**Comment by xh321** [comment]
类似的情况，就比如你在下线的时候，人家撤回了东西，你上线后只能接到撤回包

**Comment by RawDiamondMC** [comment]
> > > 重新进入消息界面效果如何 以及，仅仅是没增加撤回提示，还是说这条消息实际上已经被撤回了，再也看不到了。
> > 
> > 
> > 重新打开qqnt之后也没显示，大概是彻底没了
> 
> 有一定可能是撤回太快，qq甚至没收到这条消息，只收到了撤回包，如果是这种情况，那神仙也救不回来消息了

不是，至少3分钟以前的

**Comment by RawDiamondMC** [comment]
管理员连删了几十条消息
就最后一点留了下来

**Comment by xh321** [comment]
> 管理员连删了几十条消息 就最后一点留了下来

就是，你确定你已经看到了消息本体，然后管理员撤回了，然后就从你眼前显示“已撤回”然后再也找不到了
如果是这种情况，可能是暂存的消息满了。插件默认只在内存中缓存1000条消息（这1000条不管撤回与否，因为在储存的时候你不知道以后他们会不会被撤回），避免太多占内存。你可以修改一下插件的main.js，找到const MAX_MSG_SAVED_LIMIT=1000，将1000改大一点，然后再想办法测试一下。

**Comment by RawDiamondMC** [comment]
> 最新版已经调整为默认10000条消息了，可以更新后再看看

我觉得这个是不是可以放到设置界面？

**Comment by xh321** [comment]
> > 最新版已经调整为默认10000条消息了，可以更新后再看看
> 
> 我觉得这个是不是可以放到设置界面？

是的，可以，你可以先看看能否解决问题

**Comment by RawDiamondMC** [comment]
> > 我觉得这个是不是可以放到设置界面？
> 
> 是的，可以，你可以先看看能否解决问题

这个复现还是有点麻烦（
我先 close 这个 issue 吧
有问题再说
