### ISSUE TITLE
Mac在看到撤回消息以后，点一下别的消息框，然后再点回来，已撤回字样和颜色阴影啥的都没了，就是普通的消息了

### ISSUE THREAD

**Issue by Acheng97** [xh321/LiteLoaderQQNT-Anti-Recall#23]
有两个问题，
第一：Mac在看到撤回消息以后，点一下别的消息框，然后再点回来，已撤回字样和颜色阴影啥的都没了，就是普通的消息了
第二：当你打开一个新的聊天框，假如这个里面有一个撤回的消息，我点进去以后，撤回的消息和没有撤回的消息没有区分的标志，区分不了哪个是撤回的哪个是没撤回的

**Comment by xh321** [comment]
> 有两个问题， 第一：Mac在看到撤回消息以后，点一下别的消息框，然后再点回来，已撤回字样和颜色阴影啥的都没了，就是普通的消息了 第二：当你打开一个新的聊天框，假如这个里面有一个撤回的消息，我点进去以后，撤回的消息和没有撤回的消息没有区分的标志，区分不了哪个是撤回的哪个是没撤回的

这两个问题是同一个问题，可能是在mac下适配有问题。能否提供一下联系方式，我们远程解决，因为我本地也没有mac无法调试

**Comment by xh321** [comment]
长期不回复的话先暂时关闭issue了
