### ISSUE TITLE
连续消息合并后已撤回提示会遮挡部分气泡

### ISSUE THREAD

**Issue by shi-an** [xh321/LiteLoaderQQNT-Anti-Recall#25]
https://github.com/xiyuesaves/LiteLoaderQQNT-lite_tools/issues/26

**Comment by xh321** [comment]
已收到，会处理

**Comment by xh321** [comment]
你好，请问你用的是lite_tools哪个版本，我下载安装最新版没有合并消息功能了

**Comment by shi-an** [comment]
> 你好，请问你用的是lite_tools哪个版本，我下载安装最新版没有合并消息功能了

1.1.33 先打开头像浮动

**Comment by xh321** [comment]
0.2.25已修复，可以看一下
