### ISSUE TITLE
重启后，图片防撤回不显示

### ISSUE THREAD

**Issue by SeemWind** [xh321/LiteLoaderQQNT-Anti-Recall#28]
![image](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/50366675/d2b0572a-3085-4422-9b2a-a4b50ef0594b)
只有红框

**Comment by xh321** [comment]
有可能这张图片没有被QQ储存，或者后续被QQ删除了（一般是对方撤回太快）。如果有可能，看看能否F12检查一下，这张图对应的本地文件是否还存在。这种情况我也遇到过几次，不过是偶发性，不太好复现。

**Comment by GithubHU3** [comment]
我也遇到一样的问题，也是重启后QQ不能加载图片，我计时了一分钟后再让对方撤回图片，重启后不能显示，当图片和文字一起发送时（上传的图片），也是一分钟后，只能显示文字
![5f2c44385a579b066922e41f57d7c37c](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/119783439/a9d5028d-15fb-4ccf-8369-a9fc413cf006)

**Comment by xh321** [comment]
> 我也遇到一样的问题，也是重启后QQ不能加载图片，我计时了一分钟后再让对方撤回图片，重启后不能显示，当图片和文字一起发送时（上传的图片），也是一分钟后，只能显示文字 ![5f2c44385a579b066922e41f57d7c37c](https://private-user-images.githubusercontent.com/119783439/293592448-a9d5028d-15fb-4ccf-8369-a9fc413cf006.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMzQ4ODgsIm5iZiI6MTcwNDEzNDU4OCwicGF0aCI6Ii8xMTk3ODM0MzkvMjkzNTkyNDQ4LWE5ZDUwMjhkLTE1ZmItNGNjZi04MzY5LWE5ZmM0MTNjZjAwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMVQxODQzMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjE5ZGJlYjI4MjA0ZDk2YmUyNzczNjc4MzNjMDYyY2I4NTI2Njc0ODI3ODQ5NDZmZWMxMDA5MzJhYjNkNDQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JzeTGegbRIPZTTExxC52N0tUvKLB5zrYprW0KXXD-PA)

能稳定复现吗，什么版本QQ呢

**Comment by GithubHU3** [comment]
版本是QQ9.9.2.16183_x64
能稳定复现的

**Comment by xh321** [comment]
> 版本是QQ9.9.2.16183_x64 能稳定复现的

所以很奇怪啊，我也是这个版本，就没出现过问题。能否加一下我QQ，私发我图片试试

**Comment by GithubHU3** [comment]
已向你发送邮箱了

**Comment by xh321** [comment]
> 已发送你的邮箱了

你的QQ设置了不能被搜索，你看看改一下隐私设置？

**Comment by xh321** [comment]
新版本已修复，请及时更新
