### ISSUE TITLE
小面板独立窗口模式下，撤回失效

### ISSUE THREAD

**Issue by hacker-frok** [xh321/LiteLoaderQQNT-Anti-Recall#35]
小面板独立窗口模式下，撤回失效，只不是小面板的时候撤回才成功

小面板模式：
![image](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/157203458/f0d2210b-e929-4c78-8805-a876bdb95d55)

正常模式：
![image](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/157203458/ab35dd31-acc0-4607-9ba7-f737d498068a)

**Comment by xh321** [comment]
收到，会在近期排查

**Comment by xh321** [comment]
最新版已修复
