### ISSUE TITLE
安装插件报错

### ISSUE THREAD

**Issue by Bang0518** [xh321/LiteLoaderQQNT-Anti-Recall#36]
![image](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/30588114/d5d94596-20eb-4d2f-97b2-f18d6174a603)
![image](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/30588114/fd2592d9-104f-4cf8-8843-d3f60a613d58)
如图所示

**Comment by xh321** [comment]
这个并不是插件的问题，而且你目录权限的问题。
你liteloaderqqnt装在qq目录里，而那个目录qq每次更新都会设置权限，导致插件商店无法安装插件，你试其他插件估计也是类似的情况。
建议把liteloaderqqnt单独拿出来放在别的地方（比如D:\LLQQNT之类的），这样就不会有权限问题了。

**Comment by xh321** [comment]
当然也可能有另一种可能性，QQ运行时该文件被插件占用，插件商店要更新这个文件的时候，需要先删除，所以导致出错。该问题插件自身无法解决，是应用商店更新插件的逻辑问题。请去应用商店项目下面发ISSUE

**Comment by xh321** [comment]
看起来已经有人提过了
https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-Plugin-Store/issues/4

**Comment by Bang0518** [comment]
thanks，已解决

**Comment by whsdaks** [comment]
> 这个并不是插件的问题，而且你目录权限的问题。 你liteloaderqqnt装在qq目录里，而那个目录qq每次更新都会设置权限，导致插件商店无法安装插件，你试其他插件估计也是类似的情况。 建议把liteloaderqqnt单独拿出来放在别的地方（比如D:\LLQQNT之类的），这样就不会有权限问题了。

![image](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/49333976/cec8ecaf-5f71-47a1-82b9-22b1208aa89b)
还是有问题...
我放的是d盘根目录D:\LiteLoaderQQNT\plugins，而且整个文件夹都把只读给取消了

**Comment by xh321** [comment]
> > 这个并不是插件的问题，而且你目录权限的问题。 你liteloaderqqnt装在qq目录里，而那个目录qq每次更新都会设置权限，导致插件商店无法安装插件，你试其他插件估计也是类似的情况。 建议把liteloaderqqnt单独拿出来放在别的地方（比如D:\LLQQNT之类的），这样就不会有权限问题了。
> 
> ![image](https://private-user-images.githubusercontent.com/49333976/318280675-cec8ecaf-5f71-47a1-82b9-22b1208aa89b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5Nzg4NzQsIm5iZiI6MTcxMTk3ODU3NCwicGF0aCI6Ii80OTMzMzk3Ni8zMTgyODA2NzUtY2VjOGVjYWYtNWY3MS00N2ExLTgyYjktMjJiMTIwOGFhODliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDEzMzYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1YWUwZmNjNmIwYWZmNzBlNzlmMzhiNDBmMTI2NDJhOTI5NjIyM2MwNWE1ZWY3ZDE4ZjExYTU2ZTE5NzU0MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6DlpfPkw9UflywS7s3wUGWaJFqrvE1ArobyfiynE5rI) 还是有问题... 我放的是d盘根目录D:\LiteLoaderQQNT\plugins，而且整个文件夹都把只读给取消了

首先，这是SSL问题，意思是下载插件时你的网络问题，导致无法下载成功（Github日常抽风）
其次，这至少也是应用商店问题，在下载、安装、启用插件之前发生的问题都应该去应用商店插件下面提ISSUE
我的建议是，开全局代理（TUN模式），再下载安装。
