### ISSUE TITLE
插件商店1.1.6安装插件报错

### ISSUE THREAD

**Issue by nineKnight** [xh321/LiteLoaderQQNT-Anti-Recall#37]
![image](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/30484198/46c076c4-ab49-4121-9e16-95cc1c7d46ce)

**Comment by xh321** [comment]
这是商店下载的文件出错了，应该是你网络问题导致zip下载中断或失败，应该去商店页面提issue。不过我建议你开启TUN级别代理再重试下载。

**Comment by xh321** [comment]
更新出问题的情况已经解决，不是网络问题
