### ISSUE TITLE
反撤回不起作用

### ISSUE THREAD

**Issue by WM-wuming** [xh321/LiteLoaderQQNT-Anti-Recall#4]
qq版本9.9.0-14619 (64位)
撤回消息不会保留

**Comment by xh321** [comment]
你好，请问具体使用场景？群聊还是私聊，刚撤回的消息也不生效吗？

**Comment by WM-wuming** [comment]
> 你好，请问具体使用场景？群聊还是私聊，刚撤回的消息也不生效吗？

全部场景，刚撤回消息也不生效

**Comment by xh321** [comment]
> > 你好，请问具体使用场景？群聊还是私聊，刚撤回的消息也不生效吗？
> 
> 全部场景，刚撤回消息也不生效

你好，首先说明一下，你自己撤回自己的消息是不会拦截的哦。然后，请确认一下插件是否启用了呢，去设置里→LiteLoader配置界面→扩展里看看，是否存在防撤回，以及是否启用了，并且检查插件安装目录下是否存在重复下载的防撤回插件。若都ok的话，是否安装了其他可能会造成冲突的插件呢？麻烦给一下安装的其他插件（或者框架，例如`QQNTim`等）的列表。
因为我这边用最新版QQ测试是没问题的。
另外如果可以，附一下F12控制台的截图（先打开F12，转到Console页，然后对面撤回消息，截图一下控制台日志）

**Comment by WM-wuming** [comment]
> > > 你好，请问具体使用场景？群聊还是私聊，刚撤回的消息也不生效吗？
> > 
> > 
> > 全部场景，刚撤回消息也不生效
> 
> 你好，首先说明一下，你自己撤回自己的消息是不会拦截的哦。然后，请确认一下插件是否启用了呢，去设置里→LiteLoader配置界面→扩展里看看，是否存在防撤回，以及是否启用了，并且检查插件安装目录下是否存在重复下载的防撤回插件。若都ok的话，是否安装了其他可能会造成冲突的插件呢？麻烦给一下安装的其他插件（或者框架，例如等）的列表。 因为我这边用最新版QQ测试是没问题的。 另外如果可以，附一下F12控制台的截图（先打开F12，转到Console页，然后对面撤回消息，截图一下控制台日志）`QQNTim`

扩展里面没有，没有重复下载。安装了tim，LiteLoaderQQNT-Anti-Recall，LiteLoaderQQNT-Directly-Jump，LiteLoaderQQNT-HighlightReplies，LiteLoaderQQNT-QR-Decode，日志没有

**Comment by WM-wuming** [comment]
要不然加q聊吧

**Comment by WM-wuming** [comment]
3516595171

**Comment by WM-wuming** [comment]
> > > > 你好，请问具体使用场景？群聊还是私聊，刚撤回的消息也不生效吗？
> > > 
> > > 
> > > 全部场景，刚撤回消息也不生效
> > 
> > 
> > 你好，首先说明一下，你自己撤回自己的消息是不会拦截的哦。然后，请确认一下插件是否启用了呢，去设置里→LiteLoader配置界面→扩展里看看，是否存在防撤回，以及是否启用了，并且检查插件安装目录下是否存在重复下载的防撤回插件。若都ok的话，是否安装了其他可能会造成冲突的插件呢？麻烦给一下安装的其他插件（或者框架，例如等）的列表。 因为我这边用最新版QQ测试是没问题的。 另外如果可以，附一下F12控制台的截图（先打开F12，转到Console页，然后对面撤回消息，截图一下控制台日志）`QQNTim`
> 
> 扩展里面没有，没有重复下载。安装了tim，LiteLoaderQQNT-Anti-Recall，LiteLoaderQQNT-Directly-Jump，LiteLoaderQQNT-HighlightReplies，LiteLoaderQQNT-QR-Decode，日志没有

不对扩展里面有且开启了

**Comment by WM-wuming** [comment]
安装了qqntim不是tim打错了

**Comment by xh321** [comment]
已更新，可测试看看

**Comment by moshuiNW** [comment]
我这可以了

**Comment by WM-wuming** [comment]
已经可以了
