### ISSUE TITLE
数据库支持

### ISSUE THREAD

**Issue by HUGO123-yg** [xh321/LiteLoaderQQNT-Anti-Recall#41]
不知道作者有没有时间添加链接自己数据库的选项，

**Comment by xh321** [comment]
> 不知道作者有没有时间添加链接自己数据库的选项，

你是指mysql之类的吗？假设用户不需要的话，可能会带很多不必要的依赖。因为用的不是orm，所以没法一次性支持多个数据库。你这个需求是什么情况下需要的呢

**Comment by HUGO123-yg** [comment]
mysql，存自己的云端安全一点。不知道能不能实现

**Comment by xh321** [comment]
> mysql，存自己的云端安全一点。不知道能不能实现

反撤回还是不建议走云端，网络延迟会导致消息读取加载卡顿。后期我会考虑增加加密sqlite的支持，以解决数据不安全的问题

**Comment by HUGO123-yg** [comment]
thanks
