### ISSUE TITLE
mac安装成功无法打开QQ，提示无法打开“node.napi.node”，因为无法验证开发者。

### ISSUE THREAD

**Issue by Zheng-Ziegler** [xh321/LiteLoaderQQNT-Anti-Recall#43]
环境：Mac m1
使用install_mac.sh安装LiteLoaderQQNT成功
可正常打开QQ并使用，可正常打开设置项盒插件商店。
在插件商店安装Anti-Recall后，重启QQ，失败，探出窗口

无法打开“node.napi.node”，因为无法验证开发者。
提示两次之后，弹出A JavaScript error occurred in the main process错误窗口

检查活动监视器里，没有QQ进程。

在plugins目录删除anti_recall目录后，QQ正常启动，插件商店里防撤回为未安装状态，再次安装一样

**Comment by xh321** [comment]
你试试安装其他插件？

**Comment by Zheng-Ziegler** [comment]
> 你试试安装其他插件？ 同时截图看看A JavaScript error occurred in the main process错误窗口具体报错内容 我记得`无法打开“node.napi.node”，因为无法验证开发者。`这个报错应该有人遇到过，可能是权限问题。你可以进llqqnt的tg群问一下

安装插件商店里的 “QQ增强” 插件，正确安装并打开，弹出一个提示窗口，提示 “LLAPI版本过低”，关闭窗口后不影响使用

进入插件商店发现有个插件名为 “LLAPI”，安装之，重启后一切正常 

安装插件商店里的轻量工具箱，里面有个 “防止撤回” 的选项，正常安装并开启功能，重启后正常使用

在此期间，除了进入插件商店安装插件或修改设置选项开启功能，重启QQ以使设置生效，未做其他操作

**Comment by xh321** [comment]
> > 你试试安装其他插件？ 同时截图看看A JavaScript error occurred in the main process错误窗口具体报错内容 我记得`无法打开“node.napi.node”，因为无法验证开发者。`这个报错应该有人遇到过，可能是权限问题。你可以进llqqnt的tg群问一下
> 
> 安装插件商店里的 “QQ增强” 插件，正确安装并打开，弹出一个提示窗口，提示 “LLAPI版本过低”，关闭窗口后不影响使用
> 
> 进入插件商店发现有个插件名为 “LLAPI”，安装之，重启后一切正常
> 
> 安装插件商店里的轻量工具箱，里面有个 “防止撤回” 的选项，正常安装并开启功能，重启后正常使用
> 
> 在此期间，除了进入插件商店安装插件或修改设置选项开启功能，重启QQ以使设置生效，未做其他操作

我没有macOS无法测试复现，但是在网上查到了类似的信息
![image](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/37585529/fbaa6820-c06d-46a1-8179-1f6e8ee625ba)
看看能否解决？
大概原因是，我的反撤回插件包含一个二进制依赖，而你的macOS安全设置禁止了这个二进制的执行。

**Comment by Zheng-Ziegler** [comment]
我已经打开了从 AppStore 以外应用的安装/执行权限，这个功能不开，很多应用都用不了，如下图，不知道为啥还会不行。

这个选项打开有时也会遇到执行应用报错已损坏之类的问题，一般是网上下载的可执行的应用程序没有签名导致的，一般绕过签名就可以解决，但是你这插件遇到这个问题时，不知道是调用的哪个应用程序出了问题，报错窗口没有明确的提示，提示的都是各种各样的node和node_modules错误，看不出来是后台调用了未签名的可执行应用程序，也不知道该绕过哪个应用/目录的签名，就无所适从了

轻量工具箱已经实现了防撤回功能，我就不再折腾啦，再次感谢

![1708099694662](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/58620679/31b4e29e-fdc8-4d18-90d8-5fd0311c205c)

**Comment by xh321** [comment]
好的

**Comment by Zi-Gao** [comment]
我在macos上也遇到了这个问题，建议`sudo spctl --master-disable`关闭检查

**Comment by cddehsy** [comment]
我这报错是这个也是用不了

<img width="520" alt="iShot_2024-06-16_09 47 20" src="https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/42635049/32429540-9fff-47c8-bfe5-fe59aa2e3a51">
