### ISSUE TITLE
在轻量工具箱开启自定义背景后无“已撤回”显示

### ISSUE THREAD

**Issue by shiywhh** [xh321/LiteLoaderQQNT-Anti-Recall#45]
**未开启自定义背景：**
![QQ截图20240217130835](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/124022538/47196983-728a-491d-a473-4a2bf0f514b6)

**开启自定义背景：**
![QQ截图20240217130944](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/124022538/66c2e881-d1fa-49cd-b7bc-a82af1419b99)

**测试环境：**

- 操作系统版本：
Windows 10 专业版  22H2  19045.4046    体验Windows Feature Experience Pack 1000.19053.1000.0

- QQNT版本：
9.9.7-21484 (64位)

- 插件版本：
LiteLoaderQQNT 1.0.3（最新）
轻量工具箱 2.6.2（最新）
防撤回 0.2.36（最新）

**Comment by xh321** [comment]
开启轻量工具箱的背景功能后，它会覆盖消息样式，将反撤回的提示和效果覆盖掉。请去轻量工具箱提issue。
或者使用我开发的背景插件，不会存在兼容性问题。

**Comment by shiywhh** [comment]
好的，感谢！

**Comment by xh321** [comment]
轻量工具箱那边也在解决这个问题，可以跟进一下他们的更新
