### ISSUE TITLE
防撤回提示位置出错

### ISSUE THREAD

**Issue by TianMiao8152** [xh321/LiteLoaderQQNT-Anti-Recall#46]
只需要窗口处于打开状态即可触发，~~关闭窗口重开可恢复正常~~ ~~关闭QQ重开可以恢复~~
![b00ad3b52258d07d20b846a56e68bec0](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/83683108/117d5e89-cbb0-48cd-b3b6-0670818adf1d)
无法恢复正常

**Comment by xh321** [comment]
9.9.7-21453没有遇到问题，请问你是否开启了其他插件

**Comment by TianMiao8152** [comment]
以下为开启的插件
![image](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/83683108/49708e74-b902-403c-9629-120ced64655b)
只开启了该插件的防撤回功能

**Comment by xh321** [comment]
你把其他插件全部禁用，再测试看是否有问题。光看插件列表看不出什么，特别是轻量工具箱，他对界面修改比较多，可能会造成冲突

**Comment by TianMiao8152** [comment]
关闭插件后发现问题了，如果直接关闭轻量工具箱导致提示消失
打开阴影生效，没阴影就消失了
![image](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/83683108/42dc7acb-27fc-4573-a370-abaf09e94d00)
![image](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/83683108/8e28f742-5342-4b97-beb4-6a9d5d1d74c9)

**Comment by TianMiao8152** [comment]
![image](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/83683108/e96a58be-7635-4067-9f78-93991dcb4d18)
![image](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/83683108/f7f79432-d3f1-4463-8e43-a7d58814adad)
为啥我d的框是方形的

**Comment by TianMiao8152** [comment]
开启全部插件后变成圆形
![aff64d801db4a93d6f1abe55b894c7e4](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/83683108/d86fb7ea-7730-48ea-bf87-dccb20ec30dd)

**Comment by xh321** [comment]
关闭阴影后位置可能有些问题，这个马上修复，更新后你再试试
另外可能与轻量工具箱某些功能有兼容性问题，麻烦尝试在开启轻量工具箱的情况下逐一关闭轻量工具箱里的功能，看看哪个功能关闭后反撤回提示正常

**Comment by TianMiao8152** [comment]
暂时无法复现问题

**Comment by xh321** [comment]
轻量工具箱那边之后也会出一个更新，我这边先更新好了，你等他们那边更新后再试试

**Comment by xiyuesaves** [comment]
轻量工具箱会在稍后更新，目前还有一些优化问题没有解决。

**Comment by TianMiao8152** [comment]
好的，大佬辛苦了

**Comment by xiyuesaves** [comment]
轻量工具箱已更新

**Comment by TianMiao8152** [comment]
无法复现

**Comment by xh321** [comment]
> 无法复现

这个意思是已经解决了吗

**Comment by TianMiao8152** [comment]
> > 无法复现
> 
> 这个意思是已经解决了吗

对的，以此来看这个BUG不存在了
