### ISSUE TITLE
[adaptation] 22106 更改了部分事件名称导致防撤回失效

### ISSUE THREAD

**Issue by xiyuesaves** [xh321/LiteLoaderQQNT-Anti-Recall#49]
`nodeIKernelMsgListener/onRecvMsg` 变更为 `nodeIKernelMsgListener/onRecvActiveMsg`
`nodeIKernelMsgListener/onMsgInfoListUpdate` 变更为 `nodeIKernelMsgListener/onActiveMsgInfoUpdate`
我只用到了这两个，其他事件名称可能也有所变动，需要自己再找一下

**Comment by xh321** [comment]
ok收到

**Comment by xh321** [comment]
有PR更新我已经合并了，等有空我再完善一下
