### ISSUE TITLE
b站分享无法打开

### ISSUE THREAD

**Issue by h3x1n** [xh321/LiteLoaderQQNT-Anti-Recall#52]
点击b站分享的qq小程序，会出现打开反撤回数据库失败警告。
![image](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/39904241/39a495c2-3751-4161-9150-d479dc002794)

**Comment by xh321** [comment]
难道现在小程序改为调用QQ本体打开了吗，奇怪
我小程序早就用插件转为网页打开了（谁在PC上用小程序啊），所以我一直没发现这个问题
你点继续打开就行了，这是启动了两个QQ进程，数据库冲突了，但因为新启动的是小程序所以没有防撤回什么事
这个会在后面版本优化

**Comment by fly-over-ocean** [comment]
这个问题是LiteLoaderQQNT的问题，不安装防撤回一样打不开，要把liteloader卸了才行

**Comment by xh321** [comment]
> 这个问题是LiteLoaderQQNT的问题，不安装防撤回一样打不开，要把liteloader卸了才行

啊？不可能吧，应该还是插件的问题

**Comment by fly-over-ocean** [comment]
我已经测试过了，反撤回卸载后双击b站分享无响应，卸载liteloader后就可以正常打开了。这个问题我已经向liteloader反应了，等liteloader修好后再看看插件有没有问题吧。

**Comment by fly-over-ocean** [comment]
https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues/253#issue-2203884358

**Comment by fly-over-ocean** [comment]
> > 这个问题是LiteLoaderQQNT的问题，不安装防撤回一样打不开，要把liteloader卸了才行
> 
> 啊？不可能吧，应该还是插件的问题

https://github.com/LiteLoaderQQNT/LiteLoaderQQNT/issues/253#issue-2203884358

**Comment by xh321** [comment]
OKOK，明白了

**Comment by fly-over-ocean** [comment]
> OKOK，明白了

liteloader已经修复了这个问题了，现在b站小程序可以打开，但是还是会弹出反撤回数据库的警告。

**Comment by xh321** [comment]
警告会在之后版本修复
