### ISSUE TITLE
撤回阴影显示似乎出现异常

### ISSUE THREAD

**Issue by Starrain08** [xh321/LiteLoaderQQNT-Anti-Recall#53]
![image](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/119772101/8c355ad2-0c2c-4fdb-992f-9d640c0126ed)
撤回阴影显示异常，关闭阴影显示后已撤回字样显示异常
![image](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/119772101/10d2577b-fe43-4e46-b676-5de47c8afa30)

**Comment by xh321** [comment]
能发一下QQ版本吗

**Comment by 2055135** [comment]
![image](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/119772101/4729be85-a85f-41d1-8180-e0472a7a4757)

**Comment by xh321** [comment]
应该是新版本改了样式，等我有空统一修一修。至少旧版本应该是没问题，如果可以，可以先回滚旧版本继续用。

**Comment by 2055135** [comment]
> 应该是新版本改了样式，等我有空统一修一修。至少旧版本应该是没问题，如果可以，可以先回滚旧版本继续用。

图片撤回失效，NTQQ一直打开，开始防撤回成功，过一会图片显示失败，已经开启数据库记录

**Comment by 2055135** [comment]
版本依然是新版本

**Comment by xh321** [comment]
看来9.9.8应该还有其他改动，我听群友说图片的URL都改了，这可能是原因之一。等我有空修吧

**Comment by xh321** [comment]
已有人PR修复，请检查是否修正

**Comment by xh321** [comment]
注：图片还没修，只是修了阴影

**Comment by xh321** [comment]
0.2.45已修复图片问题
反撤回的图片只要能双击打开就是成功，预览图可能不会立即加载，需要等一段时间。
