### ISSUE TITLE
消息撤回后截拦成功，但是不显示红框和“已撤回”

### ISSUE THREAD

**Issue by bilibilijandy** [xh321/LiteLoaderQQNT-Anti-Recall#57]
如题
QQ版本：9.9.7-21484
![image](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/141329748/a3921cc8-d453-4bfc-b81d-85215f6f49b3)
日志没有任何报错
![image](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/141329748/3188f5e1-b118-4f08-9de6-9b30449b18d0)
设置页面也是空白的
![image](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/141329748/cbce6dc9-ac58-47f4-a316-5d88d3266afc)

**Comment by bilibilijandy** [comment]
补充一下
没有其他的插件

**Comment by xh321** [comment]
这个界面空白就是插件或者配置文件问题，请先前往liteloader profile目录（详见liteloader教程），确保plugins里文件夹只有反撤回一个插件，同时清空data文件夹，然后重启qq再看。

**Comment by xh321** [comment]
如无效，请用命令行打开qq查看日志报错输出
如果日志没有，请使用qq --enable-logging查看详细日志输出
如不确定可以在去掉敏感信息后在回复中贴上

**Comment by bilibilijandy** [comment]
确认只有反撤回插件

**Comment by bilibilijandy** [comment]
日志：https://paste.fastmirror.net/?85983fcfca8b4f97#mNShnNNdC1ocVW8QCMThW9EJTeUK4AUuVnV5p4WWYz6
（密码：114514）
太长了

**Comment by xh321** [comment]
知道问题了，把llqqnt profile路径移动到其他地方（设置环境变量，参考llqqnt教程）。默认位置qq上了权限，插件创建不了文件夹

**Comment by bilibilijandy** [comment]
o，谢谢啦
