### ISSUE TITLE
防撤回检测冲突异常

### ISSUE THREAD

**Issue by Starrain08** [xh321/LiteLoaderQQNT-Anti-Recall#59]
在打开小程序时会出现来自防撤回插件的
![image](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/119772101/ae123840-9f21-4827-baf6-9531fee86595)
检测多个QQ的警告
![image](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/119772101/2ba3c18e-539b-4ac7-a4fc-ea228fa728cc)

**Comment by xh321** [comment]
已知问题，会在以后修复

**Comment by xh321** [comment]
目前先屏蔽了这个弹窗
