### ISSUE TITLE
装完插件之后，qq登录久了，有些群的消息就上滑不上去

### ISSUE THREAD

**Issue by bty552** [xh321/LiteLoaderQQNT-Anti-Recall#6]
装完插件之后，qq登录久了，有些群的消息就上滑不上去
qq版本: 9.9.0-14619 (64位)

**Comment by xh321** [comment]
能否使用cmd打开QQ，然后观察一下命令行输出是否有报错？

**Comment by xh321** [comment]
可以更新一下最新版本，最新版加了命令行界面报错输出，并且修正了一部分代码，可以看看是否还会复现

**Comment by xh321** [comment]
如果后续没有问题，就暂时关闭ISSUE了，还有问题可以重新打开回复。
