### ISSUE TITLE
撤回阴影显示异常

### ISSUE THREAD

**Issue by abc15616545561** [xh321/LiteLoaderQQNT-Anti-Recall#60]
QQ版本:9.9.9-22868
![QQ截图20240413180053](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/93747842/f11a4b9a-3e10-4be6-adcd-9e82bf50793f)
基本和https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/issues/53 一样

**Comment by xh321** [comment]
一样的就不必重复提了，新版本还没完全适配

**Comment by xh321** [comment]
已有人PR修复，可检查是否修正
