### ISSUE TITLE
QQ版本: 9.9.11-24402 (64位)，无法识别防撤回插件.

### ISSUE THREAD

**Issue by sunencheng** [xh321/LiteLoaderQQNT-Anti-Recall#63]
QQ版本: 9.9.11-24402 (64位)，无法识别防撤回插件.

**Comment by xh321** [comment]
其他插件是否正常？
新版本未测试，可能存在兼容性问题（例如因为不兼容报错导致插件未加载）
如有可能请降级到9.9.7

**Comment by sunencheng** [comment]
![image](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/8297524/1693e575-d577-46dd-a89a-d695eff90867)
这些都是可以的

**Comment by sunencheng** [comment]
![image](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/8297524/03f7a98e-c0d8-4f52-9c4a-db4cb421293b)
重装最新版本后也不可以。

**Comment by xh321** [comment]
上面说了，最新版不一定兼容，建议降级9.9.7试试

**Comment by sunencheng** [comment]
> 上面说了，最新版不一定兼容，建议降级9.9.7试试

ok
