### ISSUE TITLE
图片消息防撤回异常

### ISSUE THREAD

**Issue by xiaovoaix** [xh321/LiteLoaderQQNT-Anti-Recall#67]
未打开聊天窗口时，防撤回的图片消息在撤回后打开聊天窗口图片无法显示
![image](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/58628662/38051bfa-01a4-403e-ba20-9553310d39eb)
QQ版本: 9.9.7-20979 (64位)
LLQQNT：1.1.2
插件：0.2.40

**Comment by xh321** [comment]
已知问题，以后修

**Comment by Baofen** [comment]
同样遇到此问题，自己测试一下，发图片然后不点进聊天窗口，十秒后撤回，图片并未成功加载

**Comment by scalpel-21** [comment]
确实有这个问题，啥时候能修复下

**Comment by xiaovoaix** [comment]
![image](https://github.com/user-attachments/assets/d5d1c0ea-d4c7-4d2a-a96e-a80d74781c8c)
好像……还是不行？
![image](https://github.com/user-attachments/assets/1c886381-6c5b-49e7-b9c9-7ebb7663f629)
![image](https://github.com/user-attachments/assets/3f5cb080-e0c7-4a59-b996-c2df715a837d)

**Comment by xiaovoaix** [comment]
哦，忘记更新过QQ了，那什么时候能支持下高版本QQ呢（）
