### ISSUE TITLE
防撤回插件我装上就报错 删除就可以打开 其他插件都可以用 就防撤回不能用 请问是什么原因造成的 最新版的QQ 

### ISSUE THREAD

**Issue by cloverycy** [xh321/LiteLoaderQQNT-Anti-Recall#69]
报错代码 A JASASCRIPT ERROR OCCURRED IN THE MAIN PROCESS 
![1](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/174789498/ac60c7f2-61e3-4fb9-a19e-767a6e8ebf91)
![1](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/174789498/659f6a50-e846-4246-a5f9-49764c18e998)

**Comment by xh321** [comment]
你是不是自己clone的代码，你没装依赖，建议直接去release下载完整包。clone的代码不包含依赖，需要手动npm i

**Comment by cloverycy** [comment]
谢谢解答
