### ISSUE TITLE
防撤回文件显示异常

### ISSUE THREAD

**Issue by amakerlife** [xh321/LiteLoaderQQNT-Anti-Recall#76]
LiteLoader 1.2.0 & QQNT 9.9.15-26740 on Windows11

如题，撤回的文件消息没有任何阴影/已撤回的提示。文字消息可正常显示，未开启轻量工具箱。

![image](https://github.com/user-attachments/assets/1de36c7f-fdaa-4b9a-9546-b4455e435c5b)

**Comment by xh321** [comment]
看readme，新版本并不兼容，建议降级
