### ISSUE TITLE
[feature] 关于防撤回功能增加的建议

### ISSUE THREAD

**Issue by Huasushis** [xh321/LiteLoaderQQNT-Anti-Recall#8]
目前发现防撤回貌似不能支持图片或者表情包，希望能增加这个功能。

**Comment by xh321** [comment]
这个不太行，因为如果你在撤回之前没下到原图，撤回后就读不到图片了（下载图片不由渲染层控制，渲染层只能接到本地已经下载好的原图地址来显示）。
