### ISSUE TITLE
插件在使用小程序时弹窗警告

### ISSUE THREAD

**Issue by BiliSYS** [xh321/LiteLoaderQQNT-Anti-Recall#81]
### 我已经在 [Issue Tracker](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/issues) 中找过我要提出的问题，已经找到相同问题的 issue ，但并未修复
# 环境信息
### QQNT 版本
9.9.15-26909 (64位)
### LiteLoaderQQNT 版本
1.21
### 防撤回 版本
0.2.44
### 运行环境
Windows 10 专业版 22H2 19045.4780
### 重现步骤
在使用QQNT时打开小程序则会触发防撤回插件的警告
如图所示:
![image](https://github.com/user-attachments/assets/08011245-60b2-433e-b115-1ba8d4c9ef05)

（（（麻烦大佬修复一下（

**Comment by xh321** [comment]
这个问题已知，将在我有空时更新修复

**Comment by xh321** [comment]
目前先屏蔽这个弹窗了
