### ISSUE TITLE
目前支持哪个版本的QQNT呢？

### ISSUE THREAD

**Issue by NOWorEVER** [xh321/LiteLoaderQQNT-Anti-Recall#83]
目前支持哪个版本的QQNT呢？
麻烦大佬可以说一下吗？

**Comment by xh321** [comment]
readme有写，目前支持的版本：小于等于 9.9.7-21453
当然新版也能用，只是可能有功能缺失

**Comment by NOWorEVER** [comment]
阿哲，我以为是历史文本，忘记改。我重装了好多个版本。明白了
