### ISSUE TITLE
v0.2.45 版本图片撤回后重新打开对话框 显示loading

### ISSUE THREAD

**Issue by luckksdfe** [xh321/LiteLoaderQQNT-Anti-Recall#86]
第一步：发送图片并撤回
第二步：打开其他对话框
第三步：回到原始对话框，图片就显示loading，但是双击可以查看
![image](https://github.com/user-attachments/assets/4e853d14-e70f-4a98-bec3-66f5d0b9e58a)

**Comment by Chunk7w** [comment]
我也遇到了类似的问题，在离开当前会话的情况下，如果对方撤回图片，则显示 loading 但，双击无法查看图片

**Comment by xh321** [comment]
已知情况，可能是由于预览图没有及时复制到指定位置，我会尝试修复。

**Comment by xh321** [comment]
果然是这个问题，最新版已修复
