### ISSUE TITLE
如何去除撤回消息的删除线

### ISSUE THREAD

**Issue by fgr178707** [xh321/LiteLoaderQQNT-Anti-Recall#9]
![image](https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/assets/109357981/adecd9f5-1c39-4a6e-b696-625dd2d37ddb)
如何把中间的删除线给去掉

**Comment by xh321** [comment]
这是预设的效果，如果不需要的话等我写一个配置界面吧

**Comment by fgr178707** [comment]
> 这是预设的效果，如果不需要的话等我写一个配置界面吧
好的 麻烦了

**Comment by fgr178707** [comment]
> 这是预设的效果，如果不需要的话等我写一个配置界面吧

好的 麻烦了

**Comment by xh321** [comment]
新版本已经更换样式，不再需要设置界面了
