### ISSUE TITLE
Mac能安装但是无法使用，报错

### ISSUE THREAD

**Issue by Omck-sub** [xh321/LiteLoaderQQNT-Anti-Recall#90]
Liteloader和文件复制都试过了。是不支持Mac版本么？

**Comment by Omck-sub** [comment]
![截屏2024-09-30 20 53 55](https://github.com/user-attachments/assets/0ccece82-f508-4959-9ef1-a72ff48b8a78)

**Comment by xh321** [comment]
麻烦截图一下报错什么内容？有可能是你没带上依赖，或者有可能是mac的安全限制。

**Comment by Omck-sub** [comment]
解决了解决了，第二天就好了。谢谢！
