### ISSUE TITLE
QQNT可有闪图保存功能，今天看群，有个撤回的图片裂开了，一看就是闪图

### ISSUE THREAD

**Issue by dmarkdmark** [xh321/LiteLoaderQQNT-Anti-Recall#92]
![image](https://github.com/user-attachments/assets/6e7f1c2f-5489-4061-ac65-3114c360c9a4)

**Comment by xh321** [comment]
闪图PC端可以看了吗，我一直没更新不知道

**Comment by amakerlife** [comment]
这个是普通图片消息裂了。28418 on Windows 仍然无法查看闪照

![image](https://github.com/user-attachments/assets/8a29626a-993a-4942-b9b3-afb43df539a5)

**Comment by dmarkdmark** [comment]
> 这个是普通图片消息裂了。28418 on Windows 仍然无法查看闪照
> 
> 这个是普通图片消息裂了。28418 on Windows 仍然无法查看闪照
> 
> ![image](https://private-user-images.githubusercontent.com/64350662/374223488-8a29626a-993a-4942-b9b3-afb43df539a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNTEyNzcsIm5iZiI6MTcyODM1MDk3NywicGF0aCI6Ii82NDM1MDY2Mi8zNzQyMjM0ODgtOGEyOTYyNmEtOTkzYS00OTQyLWI5YjMtYWZiNDNkZjUzOWE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDAxMjkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmMDBjOWE0MmQwNTYxYmUwMDZmYWRmMmUyNDI5YThiNzhlM2I2ODA0YjU4NGVlMTNlNzFhZTBhOGIyZDZhMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CDwDScOP4Z9X_A26eaZWf6Yt6ccjW0L7lrZQgXXL9q0)

ok，为何出现这情况，是撤回设置清理了吗

![Clip_2024-10-08_09-31-45](https://github.com/user-attachments/assets/205293a7-02a9-49c2-bca8-e687febe1567)

**Comment by xh321** [comment]
> > 这个是普通图片消息裂了。28418 on Windows 仍然无法查看闪照
> > 这个是普通图片消息裂了。28418 on Windows 仍然无法查看闪照
> > ![image](https://private-user-images.githubusercontent.com/64350662/374223488-8a29626a-993a-4942-b9b3-afb43df539a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNTEyNzcsIm5iZiI6MTcyODM1MDk3NywicGF0aCI6Ii82NDM1MDY2Mi8zNzQyMjM0ODgtOGEyOTYyNmEtOTkzYS00OTQyLWI5YjMtYWZiNDNkZjUzOWE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDAxMjkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmMDBjOWE0MmQwNTYxYmUwMDZmYWRmMmUyNDI5YThiNzhlM2I2ODA0YjU4NGVlMTNlNzFhZTBhOGIyZDZhMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CDwDScOP4Z9X_A26eaZWf6Yt6ccjW0L7lrZQgXXL9q0)
> 
> ok，为何出现这情况，是撤回设置清理了吗
> 
> ![Clip_2024-10-08_09-31-45](https://private-user-images.githubusercontent.com/114052628/374376314-205293a7-02a9-49c2-bca8-e687febe1567.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1Nzc0NDcsIm5iZiI6MTcyODU3NzE0NywicGF0aCI6Ii8xMTQwNTI2MjgvMzc0Mzc2MzE0LTIwNTI5M2E3LTAyYTktNDljMi1iY2E4LWU2ODdmZWJlMTU2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQxNjE5MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODY2OWExMTkxOWU5OGM1MDJiODk5OTZkN2FjN2RiOWY1ZjhlNjI1NGYzMDFjYWZiN2FhMDc3N2VmNDI5M2FkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WgwpEf7BL2lu6HnaV4KiE52NO_g69UxBSsAQbNXtIj0)

不是，如果被清理了都不会显示反撤回。你这个情况不太清楚是什么原因，看看能不能稳定复现吧

**Comment by dmarkdmark** [comment]
> > > 这个是普通图片消息裂了。28418 on Windows 仍然无法查看闪照
> > > 这个是普通图片消息裂了。28418 on Windows 仍然无法查看闪照
> > > ![image](https://private-user-images.githubusercontent.com/64350662/374223488-8a29626a-993a-4942-b9b3-afb43df539a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNTEyNzcsIm5iZiI6MTcyODM1MDk3NywicGF0aCI6Ii82NDM1MDY2Mi8zNzQyMjM0ODgtOGEyOTYyNmEtOTkzYS00OTQyLWI5YjMtYWZiNDNkZjUzOWE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDAxMjkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmMDBjOWE0MmQwNTYxYmUwMDZmYWRmMmUyNDI5YThiNzhlM2I2ODA0YjU4NGVlMTNlNzFhZTBhOGIyZDZhMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CDwDScOP4Z9X_A26eaZWf6Yt6ccjW0L7lrZQgXXL9q0)
> > 
> > 
> > ok，为何出现这情况，是撤回设置清理了吗ok，为何出现这情况，是撤回设置清理了吗
> > ![Clip_2024-10-08_09-31-45](https://private-user-images.githubusercontent.com/114052628/374376314-205293a7-02a9-49c2-bca8-e687febe1567.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1Nzc0NDcsIm5iZiI6MTcyODU3NzE0NywicGF0aCI6Ii8xMTQwNTI2MjgvMzc0Mzc2MzE0LTIwNTI5M2E3LTAyYTktNDljMi1iY2E4LWU2ODdmZWJlMTU2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQxNjE5MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODY2OWExMTkxOWU5OGM1MDJiODk5OTZkN2FjN2RiOWY1ZjhlNjI1NGYzMDFjYWZiN2FhMDc3N2VmNDI5M2FkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WgwpEf7BL2lu6HnaV4KiE52NO_g69UxBSsAQbNXtIj0)![Clip_2024-10-08_09-31-45](https://private-user-images.githubusercontent.com/114052628/374376314-205293a7-02a9-49c2-bca8-e687febe1567.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1Nzc0NDcsIm5iZiI6MTcyODU3NzE0NywicGF0aCI6Ii8xMTQwNTI2MjgvMzc0Mzc2MzE0LTIwNTI5M2E3LTAyYTktNDljMi1iY2E4LWU2ODdmZWJlMTU2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQxNjE5MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODY2OWExMTkxOWU5OGM1MDJiODk5OTZkN2FjN2RiOWY1ZjhlNjI1NGYzMDFjYWZiN2FhMDc3N2VmNDI5M2FkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WgwpEf7BL2lu6HnaV4KiE52NO_g69UxBSsAQbNXtIj0)
> 
> 不是，如果被清理了都不会显示反撤回。你这个情况不太清楚是什么原因，看看能不能稳定复现吧
> 
> 不是，如果被清理了都不会显示反撤回。你这个情况不太清楚是什么原因，看看能不能稳定复现吧

ok，先这接着用，看后续会不会出现这个问题

**Comment by dmarkdmark** [comment]
听他人说最新版可能会出现图片裂开
已降级使用9.9.7.20667版本
使用1.9撤回
安装成功，QQNT里面无撤回插件设置

**Comment by dmarkdmark** [comment]
日常滴滴

**Comment by dmarkdmark** [comment]
已放弃，更新QQNT最新版了，看来这个撤回图片裂开似乎就是我达到了自动清理的界限了
