### ISSUE TITLE
页面空白

### ISSUE THREAD

**Issue by 1602279568** [xh321/LiteLoaderQQNT-Anti-Recall#96]
![QQ20241016-192747](https://github.com/user-attachments/assets/d98a6344-bf1c-48b1-8bd2-90f423b13a78)
如图
LLQN版本：1.2.2
QQNT版本：9.9.15-28327

**Comment by xh321** [comment]
插件冲突，请关闭所有插件，然后逐一打开（可以先只启用防撤回看看有没有问题）
原因是有插件的渲染层出毛病了导致影响其他插件的界面

**Comment by xh321** [comment]
另外与https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/issues/93重复，你可以关注这个issue的后续进展

**Comment by 1602279568** [comment]
解决了，把\LiteLoaderQQNT\data\anti_recall直接删了让他重新生成就好了

**Comment by xh321** [comment]
ok
